version: '3.4'
services:
  web:
    build:
      context: .
      dockerfile: docker/dockerfiles/bedrock_assets
      cache_from:
        - mozorg/bedrock_assets:latest
    image: mozorg/bedrock_assets:latest
    depends_on:
      - app
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./media/:/app/media:cached
      - ./bedrock/:/app/bedrock:cached
    environment:
      BS_PROXY_URL: "app:8000"
      BS_OPEN_BROWSER: "false"
  app:
    build:
      context: .
      dockerfile: docker/dockerfiles/bedrock_test
      cache_from:
        - mozorg/bedrock:latest
    image: mozorg/bedrock_test:latest
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./bedrock/:/app/bedrock:cached
      - ./bin/:/app/bin:cached
      - ./docker/:/app/docker:cached
      - ./etc/:/app/etc:cached
      - ./lib/:/app/lib:cached
      - ./media/:/app/media:cached
      - ./root_files/:/app/root_files:cached
      - ./scripts/:/app/scripts:cached
      - ./vendor-local/:/app/vendor-local:cached
      - ./wsgi/:/app/wsgi:cached
  base:
    image: mozorg/bedrock:latest
    build:
      context: .
      dockerfile: docker/dockerfiles/bedrock_app
      cache_from:
        - mozorg/bedrock:latest
  test:
    image: mozorg/bedrock_test:latest
    env_file: .env
    volumes:
      - ./bedrock/:/app/bedrock:cached
      - ./bin/:/app/bin:cached
      - ./docker/:/app/docker:cached
      - ./etc/:/app/etc:cached
      - ./lib/:/app/lib:cached
      - ./media/:/app/media:cached
      - ./root_files/:/app/root_files:cached
      - ./scripts/:/app/scripts:cached
      - ./test/:/app/test:cached
      - ./vendor-local/:/app/vendor-local:cached
      - ./wsgi/:/app/wsgi:cached
